const GET_ALL_NOTES = 'GET_ALL_NOTES'
const GET_ALL_TAGS = 'GET_ALL_TAGS'
const CREATE_NOTE = 'CREATE_NOTE'
const CREATE_TAG = 'CREATE_TAG'
const TAG_DELETE = 'TAG_DELETE'
const TAG_REMOVE = 'TAG_REMOVE'
const NOTE_DELETE = 'NOTE_DELETE'
const ADD_TAG = 'ADD_TAG'
const UPDATE_SETTINGS = 'UPDATE_SETTINGS'
const SAVE_NOTE = 'SAVE_NOTE'

export {
    GET_ALL_NOTES,
    GET_ALL_TAGS,
    CREATE_NOTE,
    CREATE_TAG,
    TAG_DELETE,
    TAG_REMOVE,
    NOTE_DELETE,
    ADD_TAG,
    UPDATE_SETTINGS,
    SAVE_NOTE
}