module.exports = {
    TOGGLE_SEARCHED: 'TOGGLE_SEARCHED',
    UPDATE_SEARCH_TEXT: 'UPDATE_SEARCHED_TEXT',
    REFRESH_RESULTS: 'REFRESH_RESULTS',
    RE_SEARCH: 'RE_SEARCH',
    CHANGE_RESULT_TYPE: 'CHANGE_RESULT_TYPE'
}